theme = "relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  # Chemin relatif à /static
  logo = "images/logo.png"
  site_logo_hide_title = true

# Hide the Home entry.
  # Default: false
  # If shown, a Home button will appear below the search bar and the main menu.
  # It links to your the home page of the current language.

  # Masquer le titre du site dans le panneau latéral
  disableTitleInSidebar = true
