baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Soutien en programmation'
theme = "relearn"
repository_url = ""

[params]
  show_metadata = false 
  logo = "images/soutien-prog.jpeg"
  custom_css = ["css/custom.css"]
